### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by zhangyouxin** [kenberkeley/react-demo#30]
> node scripts/build.js

Binary found at D:\react-demos\react-demo\node_modules\node-sass\vendor\win32-x64-51\binding.node
Testing binary
Binary has a problem: Error: %1 is not a valid Win32 application.
\\?\D:\react-demos\react-demo\node_modules\node-sass\vendor\win32-x64-51\binding.node
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at module.exports (D:\react-demos\react-demo\node_modules\node-sass\lib\binding.js:19:10)
    at Object.<anonymous> (D:\react-demos\react-demo\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)

**Comment by kenberkeley** [comment]
参考 [⊙ 安装](https://kenberkeley.github.io/vue-demo/dist/docs/zh-cn/Getting-started.html)

**Comment by zhangyouxin** [comment]
6666 ..thanks
