### ISSUE TITLE
npm run build 报错

### ISSUE THREAD

**Issue by aiyingya** [kenberkeley/react-demo#43]
npm run build 报错：
                                     ../index.html  542 bytes          [emitted]  
fs.js:133
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:133:9)
    at Object.writeFile (fs.js:1179:14)
    at /Users/aiyingya/VScode/react-demo/build/prod.js:11:6
    at Compiler.<anonymous> (/Users/aiyingya/VScode/react-demo/node_modules/webpack/lib/Compiler.js:194:14)

**Comment by kenberkeley** [comment]
还真没见过这种报错

**Comment by kenberkeley** [comment]
rm -rf node_modules
npm i
重新安装一下？

**Comment by donaldjohn** [comment]
我也遇见这个问题
